"""
Solar-position tests.

``solaris.gee.solar_geometry`` is 144 lines of pure stdlib trigonometry with no
Earth Engine dependency, and had no tests at all. It is also load-bearing: the
shadow model's entire annual geometry rests on it.

The accuracy tests compare against a committed NREL SPA table (generated by
pvlib; see tests/data/spa_reference.csv). Measured agreement across 6 Indian
sites x 4 solstice/equinox dates x 24 hours is 0.009 deg in altitude and
0.041 deg in azimuth, so the tolerances below are loose enough not to be
brittle and tight enough to catch a genuine regression.
"""

from __future__ import annotations

import math
from datetime import UTC, date, datetime
from typing import ClassVar

import pytest

from solaris.gee.solar_geometry import (
    merge_weighted_position_sets,
    solar_positions_monthly,
    solar_positions_quarterly,
    solar_positions_single_day,
    solar_positions_yearly,
    sun_altitude_azimuth_north,
    weighted_positions_for_calendar_day,
)

# Generous relative to the measured 0.009 / 0.041 deg.
ALT_TOL_DEG = 0.05
AZ_TOL_DEG = 0.10

#: The module filters positions below this altitude. Refraction and the
#: low-precision series both degrade near the horizon, so compare above it.
MIN_ALT_FOR_COMPARISON = 2.0


def _angular_diff(a: float, b: float) -> float:
    """Smallest absolute difference between two bearings, in degrees."""
    d = abs(a - b) % 360.0
    return min(d, 360.0 - d)


def _as_utc(stamp: str) -> datetime:
    return datetime.strptime(stamp, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=UTC)


class TestAccuracyAgainstNrelSpa:
    def test_altitude_matches_spa(self, spa_reference):
        worst, worst_row = 0.0, None
        for r in spa_reference:
            if r["elevation_deg"] < MIN_ALT_FOR_COMPARISON:
                continue
            alt, _ = sun_altitude_azimuth_north(r["lat"], r["lon"], _as_utc(r["utc"]))
            err = abs(alt - r["elevation_deg"])
            if err > worst:
                worst, worst_row = err, r
        assert worst < ALT_TOL_DEG, (
            f"max altitude error {worst:.4f} deg exceeds {ALT_TOL_DEG} deg "
            f"at {worst_row['site']} {worst_row['utc']}"
        )

    def test_azimuth_matches_spa(self, spa_reference):
        worst, worst_row = 0.0, None
        for r in spa_reference:
            if r["elevation_deg"] < MIN_ALT_FOR_COMPARISON:
                continue
            _, az = sun_altitude_azimuth_north(r["lat"], r["lon"], _as_utc(r["utc"]))
            err = _angular_diff(az, r["azimuth_deg"])
            if err > worst:
                worst, worst_row = err, r
        assert worst < AZ_TOL_DEG, (
            f"max azimuth error {worst:.4f} deg exceeds {AZ_TOL_DEG} deg "
            f"at {worst_row['site']} {worst_row['utc']}"
        )

    def test_reference_table_is_nontrivial(self, spa_reference):
        """Stops an empty or truncated reference table from passing vacuously."""
        assert len(spa_reference) >= 500
        daylight = [r for r in spa_reference if r["elevation_deg"] >= MIN_ALT_FOR_COMPARISON]
        assert len(daylight) >= 200, "too few daylight rows to be a real comparison"


class TestPhysicalInvariants:
    def test_altitude_within_bounds(self, spa_reference):
        for r in spa_reference:
            alt, _ = sun_altitude_azimuth_north(r["lat"], r["lon"], _as_utc(r["utc"]))
            assert -90.0 <= alt <= 90.0

    def test_azimuth_within_bounds(self, spa_reference):
        for r in spa_reference:
            _, az = sun_altitude_azimuth_north(r["lat"], r["lon"], _as_utc(r["utc"]))
            assert 0.0 <= az < 360.0

    def test_summer_solstice_peak_altitude_at_delhi(self):
        """
        Peak altitude on the June solstice is 90 - |lat - declination|, which at
        Delhi (28.6139 N) with declination +23.44 is 84.83 deg. Scanned at
        1-minute steps to find the true maximum rather than a sampled one.
        """
        lat, lon = 28.6139, 77.2090
        peak = max(
            sun_altitude_azimuth_north(lat, lon, datetime(2023, 6, 21, h, m, tzinfo=UTC))[0]
            for h in range(24)
            for m in range(60)
        )
        expected = 90.0 - abs(lat - 23.44)
        assert peak == pytest.approx(expected, abs=0.2), (
            f"solstice peak {peak:.2f} deg, expected ~{expected:.2f} deg"
        )

    def test_northern_noon_faces_south(self):
        """North of the declination, the sun bears ~180 deg at local noon."""
        alts = [
            sun_altitude_azimuth_north(28.6, 77.2, datetime(2023, 12, 21, h, m, tzinfo=UTC))
            for h in range(24)
            for m in range(0, 60, 10)
        ]
        _, az = max(alts, key=lambda t: t[0])
        assert _angular_diff(az, 180.0) < 15.0, f"expected south-facing noon, got {az:.1f}"

    def test_southern_noon_faces_north(self):
        """South of the declination, the bearing flips -- pins the sign convention."""
        alts = [
            sun_altitude_azimuth_north(-33.9, 18.4, datetime(2023, 12, 21, h, m, tzinfo=UTC))
            for h in range(24)
            for m in range(0, 60, 10)
        ]
        _, az = max(alts, key=lambda t: t[0])
        assert _angular_diff(az, 0.0) < 15.0, f"expected north-facing noon, got {az:.1f}"

    def test_naive_datetime_rejected(self):
        with pytest.raises(ValueError, match="timezone-aware"):
            sun_altitude_azimuth_north(28.6, 77.2, datetime(2023, 6, 21, 7, 0))

    def test_deterministic(self):
        when = datetime(2023, 6, 21, 7, 0, tzinfo=UTC)
        first = sun_altitude_azimuth_north(28.6, 77.2, when)
        for _ in range(5):
            assert sun_altitude_azimuth_north(28.6, 77.2, when) == first


class TestWeightedPositionSets:
    BUILDERS: ClassVar[list] = [
        ("yearly", lambda: solar_positions_yearly(28.6, 77.2, 2023)),
        ("quarterly-q1", lambda: solar_positions_quarterly(28.6, 77.2, 2023, 1)),
        ("quarterly-q3", lambda: solar_positions_quarterly(28.6, 77.2, 2023, 3)),
        ("monthly-jun", lambda: solar_positions_monthly(28.6, 77.2, 2023, 6)),
        ("monthly-dec", lambda: solar_positions_monthly(28.6, 77.2, 2023, 12)),
        ("single-day", lambda: solar_positions_single_day(28.6, 77.2, date(2023, 6, 21))),
    ]
    IDS: ClassVar[list[str]] = [name for name, _ in BUILDERS]

    @pytest.mark.parametrize("name,build", BUILDERS, ids=IDS)
    def test_weights_sum_to_one(self, name, build):
        """
        The shadow model multiplies each position mask by its weight and sums.
        Weights that do not total 1 silently scale shadow_frequency -- exactly
        what the API-side ``pos[::2]`` thinning would have caused. Regression
        guard for that class of bug.
        """
        assert sum(p[2] for p in build()) == pytest.approx(1.0, abs=1e-9)

    @pytest.mark.parametrize("name,build", BUILDERS, ids=IDS)
    def test_shape_and_bounds(self, name, build):
        positions = build()
        assert positions, "no positions returned"
        for alt, az, weight, hour in positions:
            assert alt >= 2.0, "altitude floor not applied"
            assert 0.0 <= az < 360.0
            assert 0.0 < weight <= 1.0
            assert isinstance(hour, int)
            assert 0 <= hour <= 23

    @pytest.mark.parametrize("name,build", BUILDERS, ids=IDS)
    def test_weights_are_positive_and_sin_weighted(self, name, build):
        for alt, _az, weight, _hour in build():
            assert weight > 0
            assert math.sin(math.radians(alt)) > 0

    def test_counts_stay_below_api_thinning_threshold(self):
        """
        The API halved the position list above 42 entries without renormalising
        the weights. No builder reaches 42, which is why that bug never fired.
        Pin it so the dead branch cannot quietly come back to life.
        """
        for name, build in self.BUILDERS:
            n = len(build())
            assert n <= 42, f"{name} returned {n} positions; the thinning bug could fire"

    def test_polar_winter_falls_back_to_sentinel(self):
        """A day with no sun above the floor must not yield an empty list."""
        assert weighted_positions_for_calendar_day(80.0, 20.0, date(2023, 12, 21)) == [
            (45.0, 180.0, 1.0, 12)
        ]

    def test_merging_empty_sets_does_not_divide_by_zero(self):
        assert merge_weighted_position_sets([[], []]) == [(45.0, 180.0, 1.0, 12)]

    def test_merge_renormalises_and_preserves_count(self):
        june = solar_positions_single_day(28.6, 77.2, date(2023, 6, 21))
        december = solar_positions_single_day(28.6, 77.2, date(2023, 12, 21))
        merged = merge_weighted_position_sets([june, december])
        assert sum(p[2] for p in merged) == pytest.approx(1.0, abs=1e-9)
        assert len(merged) == len(june) + len(december)

    def test_invalid_quarter_rejected(self):
        with pytest.raises(ValueError, match="quarter"):
            solar_positions_quarterly(28.6, 77.2, 2023, 5)

    def test_invalid_month_rejected(self):
        with pytest.raises(ValueError, match="month"):
            solar_positions_monthly(28.6, 77.2, 2023, 13)

    def test_summer_day_has_more_positions_than_winter(self):
        """Sanity check that the altitude filter responds to season."""
        june = solar_positions_single_day(28.6, 77.2, date(2023, 6, 21))
        december = solar_positions_single_day(28.6, 77.2, date(2023, 12, 21))
        assert len(june) > len(december)
